[book]
authors = ["kangtae49"]
language = "en"
multilingual = false
src = "src"
title = "Rust Book"

[output.html]
default-theme = "ayu"
additional-css = ["src/theme/css/custom.css"]


[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
runnable = true

